package com.geotab.mobile.sdk.models.enums

enum class GeotabDriveError {
    MODULE_FUNCTION_ARGUMENT_ERROR,
    MODULE_GEOLOCATION_ERROR,
    INVALID_CALL_ERROR,
    API_CALL_TIMEOUT_ERROR,
    JS_ISSUED_ERROR,
    NOTIFICATION_NOT_FOUND,
    CAPTURE_IMAGE_ERROR,
    PICK_IMAGE_ERROR,
    FILE_EXCEPTION,
    EVENT_PARSING_EXCEPTION,
    SOCKET_PERMISSION_DENIED_EXCEPTION,
    SOCKET_ACCESSORY_DETACHED_EXCEPTION,
    SOCKET_ACCESSORY_NOT_AVAILABLE_EXCEPTION,
    SOCKET_WRITE_EXCEPTION,
    MODULE_BLE_ERROR,
    MODULE_SAML_ERROR,
    MODULE_SPEECH_ERROR,
    MODULE_NOTIFICATION_ERROR,
    INVALID_JSON,
    INVALID_MODULE_EVENT,
    NO_CONTEXT,
    OPERATION_CALL_EXCEPTION,
    OPENCAB_ERROR,
    STORAGE_MODULE_ERROR,
    OVERLAY_ERROR
}
